---
title: "Fitbit DailyData Metrics"
author: "Pranav Anbarasu"
date: "`r Sys.Date()`"
output:
  html_document:
    embed-resources: true
    toc: true
    toc_float:
      smooth-scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = '~/RECOVER-MHDR-Analysis/')
knitr::opts_chunk$set(fig.height = 8)
knitr::opts_chunk$set(fig.width = 15)
```

```{r libraries and archive version, include=FALSE, warning=FALSE, message=FALSE}
library(lubridate)
library(stringr)
library(dplyr)
library(arrow)
library(tidyr)
library(synapser)
library(knit2synapse)
library(ggpubr)

synapser::synLogin(authToken = Sys.getenv("SYNAPSE_AUTH_TOKEN"))

ARCHIVE_VERSION <- "2023-12-06"

if (!(ARCHIVE_VERSION %in% list.dirs("./dashboards/fitbit-dailydata-metrics/rendered-dfs/"))) {
  dir.create(glue::glue("./dashboards/fitbit-dailydata-metrics/rendered-dfs/{ARCHIVE_VERSION}/"))
}
```

```{r access data, include=FALSE, message=FALSE, warning=FALSE}
synLogin(authToken = Sys.getenv("SYNAPSE_AUTH_TOKEN"))

sts_token <- 
  synapser::synGetStsStorageToken(
    entity = 'syn52506069',
    permission = 'read_only',
    output_format = 'json')

s3 <- 
  arrow::S3FileSystem$create(
    access_key = sts_token$accessKeyId,
    secret_key = sts_token$secretAccessKey,
    session_token = sts_token$sessionToken,
    region="us-east-1")

bucket_path <- paste0(sts_token$bucket, '/', 
                      sts_token$baseKey, '/', 
                      ARCHIVE_VERSION, '/')

dataset_list <- 
  s3$GetFileInfo(
    arrow::FileSelector$create(
      bucket_path, 
      recursive=F))

dataset_paths <- character()
for (dataset in dataset_list) {
  dataset_paths <- c(dataset_paths, dataset$path)
}
```

```{r open datasets, include=FALSE}
fitbitdailydata <- 
  arrow::open_dataset(
    s3$path(
      dataset_paths[grep(".*dataset_fitbitdailydata$", dataset_paths)])) %>% 
  mutate(
    HeartRateIntradayMinuteCount = as.numeric(HeartRateIntradayMinuteCount),
    Steps = as.numeric(Steps),
    SpO2_Avg = as.numeric(SpO2_Avg),
    Hrv_DailyRmssd = as.numeric(Hrv_DailyRmssd)) %>% 
  rename(
    spo2_avg = SpO2_Avg,
    hrv = Hrv_DailyRmssd) %>% 
  collect()

enrolledparticipants <- 
  arrow::open_dataset(
    s3$path(
      dataset_paths[grep(".*dataset_enrolledparticipants$", dataset_paths)])) %>% 
  collect()
```

```{r functions, include=FALSE}
num_records_total <- function(df, measure) {
  df %>% 
    select(all_of(measure)) %>% 
    nrow()
}

num_records_complete <- function(df, measure) {
  df %>% 
    select(all_of(measure)) %>% 
    drop_na() %>% 
    nrow()
}

num_records_complete_nonzero <- function(df, measure) {
  df %>%
    select(all_of(measure)) %>%
    filter(.[[measure]]!=0) %>%
    drop_na() %>%
    nrow()
}

num_participants_with_records <- function(df, measure) {
  df$ParticipantIdentifier[
    !is.na(df[[measure]])
  ] %>%
    unique() %>%
    length()
}

num_participants_with_records_nonzero <- function(df, measure) {
  df$ParticipantIdentifier[
    !is.na(df[[measure]]) &
      df[[measure]]!=0
  ] %>%
    unique() %>%
    length()
}

days_present_nonzero_per_participant <- function(df, measure) {
  df %>% 
    select(ParticipantIdentifier, Date, measure) %>% 
    mutate(Date = as_date(Date)) %>% 
    drop_na() %>% 
    filter(.[[measure]]!=0) %>% 
    group_by(ParticipantIdentifier) %>% 
    distinct(Date, .keep_all = T) %>% 
    summarise(days_present_nonzero = n()) %>% 
    ungroup()
}

avg_days_present_nonzero <- function(df, col) {
  mean(df[[col]])
}
```

```{r heart rate calculations, include=FALSE}
days_present_nonzero_per_participant_hr_df <- 
  days_present_nonzero_per_participant(fitbitdailydata, "HeartRateIntradayMinuteCount")

kd <- density(days_present_nonzero_per_participant_hr_df$days_present_nonzero, bw = "SJ")
plot(kd, main = "Number of Days of Data per Participant", sub = "HeartRate: HeartRateIntradayMinuteCount")
polygon(kd, col='lightblue', border='black')

wear_time_enrollment_df_hr <- 
  merge(x = fitbitdailydata %>% select(ParticipantIdentifier, Date, HeartRateIntradayMinuteCount), 
             y = enrolledparticipants %>% select(ParticipantIdentifier, EnrollmentDate)) %>% 
  mutate(Date = as_date(Date),
         EnrollmentDate = as_date(EnrollmentDate)) %>% 
  drop_na()

avg_total_wear_time_since_enrollment_per_participant <- 
  wear_time_enrollment_df_hr %>% 
  filter(Date>=EnrollmentDate) %>% 
  group_by(ParticipantIdentifier) %>% 
  mutate(last_date = max(Date)) %>% 
  mutate(days = last_date-EnrollmentDate+1) %>% 
  mutate(n = n()) %>% 
  summarise(
    avg_wear_time_mins = round(sum(HeartRateIntradayMinuteCount)/as.numeric(first(days)), 3), 
    avg_wear_time_percent = round((sum(HeartRateIntradayMinuteCount)/as.numeric(first(days)))/1439, 3))

kd2 <- density(avg_total_wear_time_since_enrollment_per_participant$avg_wear_time_percent, bw = "SJ")
plot(kd2, main = "Average Total Wear Time Since Enrollment", sub = "HeartRate: HeartRateIntradayMinuteCount")
polygon(kd2, col='lightblue', border='black')

days_enrollment_df_hr <- 
  merge(x = fitbitdailydata %>% select(ParticipantIdentifier, Date, HeartRateIntradayMinuteCount), 
        y = enrolledparticipants %>% select(ParticipantIdentifier, EnrollmentDate)) %>% 
  mutate(Date = as_date(Date),
         EnrollmentDate = as_date(EnrollmentDate)) %>% 
  drop_na() %>% 
  filter(HeartRateIntradayMinuteCount!=0)

proportion_days_since_enrollment_per_participant_hr <-
  days_enrollment_df_hr %>%
  group_by(ParticipantIdentifier) %>%
  filter(Date>=EnrollmentDate) %>%
  summarise(n_days = n(),
            dt = as.numeric(max(Date)-min(EnrollmentDate)+1)) %>% 
  mutate(adherence_proportion = n_days/dt)

insights_hr <- 
  data.frame(
    "device" = "fitbit",
    "category" = "heartrate",
    "measure" = "HeartRateIntradayMinuteCount",
    "n_records" = num_records_total(fitbitdailydata, "HeartRateIntradayMinuteCount"),
    "n_complete_records" = num_records_complete(fitbitdailydata, "HeartRateIntradayMinuteCount"),
    "n_complete_nonzero_records" = num_records_complete_nonzero(fitbitdailydata, "HeartRateIntradayMinuteCount"),
    "n_participants_with_complete_records" = num_participants_with_records(fitbitdailydata, "HeartRateIntradayMinuteCount"),
    "n_participants_with_complete_nonzero_records" = num_participants_with_records_nonzero(fitbitdailydata, "HeartRateIntradayMinuteCount"),
    "avg_days_of_complete_nonzero_data" = avg_days_present_nonzero(days_present_nonzero_per_participant_hr_df, "days_present_nonzero"),
    "avg_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_hr$n_days),
    "avg_proportion_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_hr$adherence_proportion),
    "avg_total_wear_time_since_enrollment_all_participants" = mean(avg_total_wear_time_since_enrollment_per_participant$avg_wear_time_mins),
    "avg_total_wear_time_proportion_since_enrollment_all_participants" = mean(avg_total_wear_time_since_enrollment_per_participant$avg_wear_time_percent)
    )
```

```{r activity steps calculations}
# Fitbit Activity steps -------------------------------------------
days_present_nonzero_per_participant_steps_df <- days_present_nonzero_per_participant(fitbitdailydata, "Steps")

kd3 <- density(days_present_nonzero_per_participant_steps_df$days_present_nonzero, bw = "SJ")
plot(kd3, main = "Number of Days of Data per Participant", sub = "Activity: Steps")
polygon(kd3, col='lightblue', border='black')

days_enrollment_df_steps <- 
  merge(x = fitbitdailydata %>% select(ParticipantIdentifier, Date, Steps), 
        y = enrolledparticipants %>% select(ParticipantIdentifier, EnrollmentDate)) %>% 
  mutate(Date = as_date(Date),
         EnrollmentDate = as_date(EnrollmentDate)) %>% 
  drop_na() %>% 
  filter(Steps!=0)

proportion_days_since_enrollment_per_participant_steps <-
  days_enrollment_df_steps %>%
  group_by(ParticipantIdentifier) %>%
  filter(Date>=EnrollmentDate) %>%
  summarise(n_days = n(),
            dt = as.numeric(max(Date)-min(EnrollmentDate)+1)) %>% 
  mutate(adherence_proportion = n_days/dt)

kd4 <- density(proportion_days_since_enrollment_per_participant_steps$adherence_proportion, bw = "ucv")
plot(kd4, main = "Proportion of Number of Days of Data Since Enrollment per Participant", sub = "Activity: Steps")
polygon(kd4, col='lightblue', border='black')

insights_steps <- 
  data.frame(
    "device" = "fitbit",
    "category" = "activity",
    "measure" = "steps",
    "n_records" = num_records_total(fitbitdailydata, "Steps"),
    "n_complete_records" = num_records_complete(fitbitdailydata, "Steps"),
    "n_complete_nonzero_records" = num_records_complete_nonzero(fitbitdailydata, "Steps"),
    "n_participants_with_complete_records" = num_participants_with_records(fitbitdailydata, "Steps"),
    "n_participants_with_complete_nonzero_records" = num_participants_with_records_nonzero(fitbitdailydata, "Steps"),
    "avg_days_of_complete_nonzero_data" = avg_days_present_nonzero(days_present_nonzero_per_participant(fitbitdailydata, "Steps"), "days_present_nonzero"),
    "avg_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_steps$n_days),
    "avg_proportion_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_steps$adherence_proportion)
  )
```

```{r spo2 calculations}
days_present_nonzero_per_participant_spo2_df <- days_present_nonzero_per_participant(fitbitdailydata, "spo2_avg")

kd5 <- density(days_present_nonzero_per_participant_spo2_df$days_present_nonzero, bw = "SJ")
plot(kd5, main = "Number of Days of Data per Participant", sub = "spo2")
polygon(kd5, col='lightblue', border='black')

days_enrollment_df_spo2 <- 
  merge(x = fitbitdailydata %>% select(ParticipantIdentifier, Date, spo2_avg), 
        y = enrolledparticipants %>% select(ParticipantIdentifier, EnrollmentDate)) %>% 
  mutate(Date = as_date(Date),
         EnrollmentDate = as_date(EnrollmentDate)) %>% 
  drop_na() %>% 
  filter(spo2_avg!=0)

proportion_days_since_enrollment_per_participant_spo2 <-
  days_enrollment_df_spo2 %>%
  group_by(ParticipantIdentifier) %>%
  filter(Date>=EnrollmentDate) %>%
  summarise(n_days = n(),
            dt = as.numeric(max(Date)-min(EnrollmentDate)+1)) %>% 
  mutate(adherence_proportion = n_days/dt)

kd6 <- density(proportion_days_since_enrollment_per_participant_spo2$adherence_proportion, bw = "ucv")
plot(kd6, main = "Proportion of Number of Days of Data Since Enrollment per Participant", sub = "spo2")
polygon(kd6, col='lightblue', border='black')

insights_spo2 <- 
  data.frame(
    "device" = "fitbit",
    "category" = "spo2",
    "measure" = "spo2",
    "n_records" = num_records_total(fitbitdailydata, "spo2_avg"),
    "n_complete_records" = num_records_complete(fitbitdailydata, "spo2_avg"),
    "n_complete_nonzero_records" = num_records_complete_nonzero(fitbitdailydata, "spo2_avg"),
    "n_participants_with_complete_records" = num_participants_with_records(fitbitdailydata, "spo2_avg"),
    "n_participants_with_complete_nonzero_records" = num_participants_with_records_nonzero(fitbitdailydata, "spo2_avg"),
    "avg_days_of_complete_nonzero_data" = avg_days_present_nonzero(days_present_nonzero_per_participant(fitbitdailydata, "spo2_avg"), "days_present_nonzero"),
    "avg_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_spo2$n_days),
    "avg_proportion_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_spo2$adherence_proportion)
  )

```

```{r hrv calculations}
days_present_nonzero_per_participant_hrv_df <- days_present_nonzero_per_participant(fitbitdailydata, "hrv")

kd7 <- density(days_present_nonzero_per_participant_hrv_df$days_present_nonzero, bw = "SJ")
plot(kd7, main = "Number of Days of Data per Participant", sub = "hrv")
polygon(kd7, col='lightblue', border='black')

days_enrollment_df_hrv <- 
  merge(x = fitbitdailydata %>% select(ParticipantIdentifier, Date, hrv), 
        y = enrolledparticipants %>% select(ParticipantIdentifier, EnrollmentDate)) %>% 
  mutate(Date = as_date(Date),
         EnrollmentDate = as_date(EnrollmentDate)) %>% 
  drop_na() %>% 
  filter(hrv!=0)

proportion_days_since_enrollment_per_participant_hrv <-
  days_enrollment_df_hrv %>%
  group_by(ParticipantIdentifier) %>%
  filter(Date>=EnrollmentDate) %>%
  summarise(n_days = n(),
            dt = as.numeric(max(Date)-min(EnrollmentDate)+1)) %>% 
  mutate(adherence_proportion = n_days/dt)

kd8 <- density(proportion_days_since_enrollment_per_participant_hrv$adherence_proportion, bw = "ucv")
plot(kd8, main = "Proportion of Number of Days of Data Since Enrollment per Participant", sub = "hrv")
polygon(kd8, col='lightblue', border='black')

insights_hrv <- 
  data.frame(
    "device" = "fitbit",
    "category" = "hrv",
    "measure" = "hrv",
    "n_records" = num_records_total(fitbitdailydata, "hrv"),
    "n_complete_records" = num_records_complete(fitbitdailydata, "hrv"),
    "n_complete_nonzero_records" = num_records_complete_nonzero(fitbitdailydata, "hrv"),
    "n_participants_with_complete_records" = num_participants_with_records(fitbitdailydata, "hrv"),
    "n_participants_with_complete_nonzero_records" = num_participants_with_records_nonzero(fitbitdailydata, "hrv"),
    "avg_days_of_complete_nonzero_data" = avg_days_present_nonzero(days_present_nonzero_per_participant(fitbitdailydata, "hrv"), "days_present_nonzero"),
    "avg_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_hrv$n_days),
    "avg_proportion_n_days_since_enrollment_all_participants" = mean(proportion_days_since_enrollment_per_participant_hrv$adherence_proportion)
  )
```

```{r bind all four calculations dfs}
insights <- bind_rows(insights_hr, insights_steps, insights_spo2, insights_hrv)

fitbit_data_metrics <- 
  data.frame(Type = insights$category, 
             Participants = insights$n_participants_with_complete_nonzero_records,
             Records = insights$n_complete_nonzero_records, 
             Average_Days_and_Since_Enrollment = paste(round(insights$avg_days_of_complete_nonzero_data, 1), '(', round(insights$avg_n_days_since_enrollment_all_participants, 1), ')'), 
             Proportion_Days_Present_Since_Enrollment = round(insights$avg_proportion_n_days_since_enrollment_all_participants, 3))

write.csv(insights, './dashboards/fitbit-dailydata-metrics/rendered_dfs/insights.csv')
write.csv(fitbit_data_metrics, './dashboards/fitbit-dailydata-metrics/rendered_dfs/fitbit_dailydatadata_metrics.csv')
```


## Code used 

```{r provenance, echo=FALSE, results='asis'}
this_file_path <- "dashboards/fitbit-dailydata-metrics/fitbit-dailydata-metrics.Rmd"

latest_file_commit <- 
  gh::gh("/repos/:owner/:repo/commits", 
         owner = "pranavanba", 
         repo = "RECOVER-MHDR-Analysis", 
         path = this_file_path)[[1]]$commit$url %>% 
  {gsub("https://api.github.com/repos/", "https://github.com/", .)} %>% {gsub("/git/commits/", "/blob/", .)} %>% glue::glue("/{this_file_path}")

cat("[GitHub Code](", latest_file_commit, ")")
```


```{r knit into synapse, eval=FALSE, include=FALSE}
synapseclient <- reticulate::import("synapseclient")
syn_temp <- synapseclient$Synapse()
syn_temp$login(authToken = Sys.getenv("SYNAPSE_AUTH_TOKEN"))

### Please install v1.28 of reticulate, as this is the needed version for synapser
### devtools::install_version("reticulate", version = "1.28", repos = "http://cran.us.r-project.org")
DASHBOARD_FOLDER_SYNID <- "syn53216321"
FOLDER_NAME <- "Fitbit DailyData Metrics"

knit2synapse:::createAndKnitToFolderEntityClient(
  file = "dashboards/fitbit-dailydata-metrics/fitbit-dailydata-metrics.Rmd",
  parentId = DASHBOARD_FOLDER_SYNID,
  folderName = FOLDER_NAME)
```
