---
title: "dashboard_fitbit_sleep_vs_otherData"
output: html_document
date: "`r base::date()`"
chunk_output_type: console
---

```{r knit into synapse, eval=FALSE, include=FALSE}
#### Block with parameters (archive version, synapse parentId and synapse folder name) for knit2Synapse
library(synapser)
library(knit2synapse)
# devtools::install_github("jgockley62/knit2synapse")
library(githubr)
# devtools::install_github("brian-bot/githubr")

synapser::synLogin()

######### change knit2synapse to Jake's version

#### ARCHIVE VERSION
ARCHIVE_VERSION <- '2023-08-02'  ## UPDATE archive version here

#### GitHub Token
gtToken = "<YOUR GITHUB PERSONAL TOKEN>"

## New lines for calling synapseclient
synapseclient <- reticulate::import("synapseclient")
syn_temp <- synapseclient$Synapse()
syn_temp$login() # is fails use syn_temp$login(authToken = <yourPAT>)
# get your PAT at "https://www.synapse.org/#!PersonalAccessTokens:"

### Note the new function being called from knit2synapse
### Please install this version of knit2synapse
### devtools::install_github("jgockley62/knit2synapse")

### Please install v1.28 of reticulate, as this is the needed version for synapser
### devtools::install_version("reticulate", version = "1.28", repos = "http://cran.us.r-project.org")
knit2synapse:::createAndKnitToFolderEntityClient(file = "dashboard_fitbit_sleep_vs_otherData.Rmd",
                                          parentId = "syn52961736",
                                          folderName = ARCHIVE_VERSION)
```

```{r required libraries, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
########
# Required Libraries
########
library(synapser)
library(tidyverse)
library(arrow)
library(lubridate)
library(knitr)
```

```{r required functions, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
## Custom functions for data processing
summarizeData <- function(pDat){
  
  # print(nrow(pDat))
  
  pDat_dataset <- paste0(pDat$dataset %>% unique(), collapse = ',')
  
  pDat_return <- pDat %>% 
    dplyr::select(-dataset) %>% 
    unique() %>% 
    dplyr::mutate(dataset = pDat_dataset)
  
  return(pDat_return)
  
}

```

```{r setup and download, include=FALSE, warning=FALSE, message=FALSE}
############################
## Get Sleep data
############################
## Set up Token access
sts_token <- synapser::synGetStsStorageToken(entity = 'syn52506069', # sts enabled destination folder
                                             permission = 'read_only',   # request a read only token
                                             output_format = 'json')

s3_external <- arrow::S3FileSystem$create(access_key = sts_token$accessKeyId,
                                          secret_key = sts_token$secretAccessKey,
                                          session_token = sts_token$sessionToken,
                                          region="us-east-1")

## Get list of datasets in the S3 bucket
base_s3_uri_external <- paste0(sts_token$bucket, "/", sts_token$baseKey,'/',ARCHIVE_VERSION)
parquet_datasets_external <- s3_external$GetFileInfo(arrow::FileSelector$create(base_s3_uri_external, recursive=F))

## Get all valid datasets
i <- 0
valid_paths <- character()
for (dataset in parquet_datasets_external) {
  if (grepl('recover-main-project/main/archive/', dataset$path, perl = T, ignore.case = T)) {
    i <- i+1
    cat(i)
    cat(":", dataset$path, "\n")
    valid_paths <- c(valid_paths, dataset$path)
  }
}

## Get dataset type (for eg., dataset_enrolledparticipants)
valid_paths_ext_df <- valid_paths %>% 
  as.data.frame() %>% 
  `colnames<-`('parquet_path_external') %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(datasetType = str_split(parquet_path_external,'/')[[1]][5]) %>%
  dplyr::ungroup()

#### Get the sleep data in
dataset_path <- valid_paths[[9]]
fitbit_sleeplogs <-  arrow::open_dataset(s3_external$path(as.character(dataset_path))) %>% dplyr::collect()

dataset_path <- valid_paths[[1]]
enrolledparticipants <-  arrow::open_dataset(s3_external$path(as.character(dataset_path))) %>% dplyr::collect()

```

```{r Summarize data for analysis and plots,  echo=FALSE, warning=FALSE, message=FALSE}
############
## Summary of data
############
####### SLEEP
sleep_summary <- fitbit_sleeplogs %>% 
  dplyr::select(ParticipantIdentifier, StartDate, EndDate) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(Date = as.Date(StartDate) %>% as.character()) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(dataset = 'fitbitsleeplogs')


####### Other Fitbit Measures
####### 
dataset_path <- valid_paths[[4]]
fitbit_data <-  arrow::open_dataset(s3_external$path(as.character(dataset_path))) %>% dplyr::collect()
activitylogs_summary <- fitbit_data %>% 
  dplyr::select(ParticipantIdentifier, StartDate, EndDate) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(Date = as.character(as.Date(StartDate))) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(dataset = 'activitylogs')


dataset_path <- valid_paths[[5]]
fitbit_data <-  arrow::open_dataset(s3_external$path(as.character(dataset_path))) %>% dplyr::collect()
dailydata_summary <- fitbit_data %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(Date = as.character(as.Date(Date))) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ParticipantIdentifier, Date) %>% 
  dplyr::mutate(dataset = 'dailydata')


dataset_path <- valid_paths[[8]]
fitbit_data <-  arrow::open_dataset(s3_external$path(as.character(dataset_path))) %>% dplyr::collect()
restingHR_summary <- fitbit_data %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(Date = as.character(as.Date(Date))) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ParticipantIdentifier, Date) %>% 
  dplyr::mutate(dataset = 'restingHR')


### merge em all
aa <- sleep_summary %>% 
  dplyr::full_join(activitylogs_summary) %>% 
  dplyr::full_join(restingHR_summary) %>% 
  dplyr::full_join(dailydata_summary) %>% 
  dplyr::select(ParticipantIdentifier,
                Date,
                dataset) %>% 
  unique() %>% 
  na.omit() %>% 
  dplyr::group_by(ParticipantIdentifier, Date) %>% 
  do(summarizeData(.)) %>% 
  dplyr::mutate(dailydata = ifelse(grepl('dailydata',dataset),TRUE,FALSE)) %>% 
  dplyr::mutate(activitylogs = ifelse(grepl('activitylogs',dataset),TRUE,FALSE)) %>% 
  dplyr::mutate(restingHR = ifelse(grepl('restingHR',dataset),TRUE,FALSE)) %>% 
  dplyr::mutate(fitbitsleeplogs = ifelse(grepl('fitbitsleeplogs',dataset),TRUE,FALSE)) %>% 
  dplyr::mutate(otherData = ifelse(dailydata || activitylogs || restingHR, TRUE, FALSE)) %>% 
  ungroup() %>% 
  dplyr::left_join(enrolledparticipants %>% 
                     dplyr::select(ParticipantIdentifier, EnrollmentDate) %>% 
                     dplyr::mutate(days_enrolled = lubridate::days(Sys.Date() - as.Date(EnrollmentDate)))) %>% 
  dplyr::filter(Date >= EnrollmentDate)   # records after enrollment

  aa$row <- rownames(aa)

aa3 <- aa %>% 
  dplyr::select(row, dailydata, activitylogs, restingHR, fitbitsleeplogs, otherData) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(dailydata = as.integer(dailydata),
                activitylogs = as.integer(activitylogs),
                restingHR = as.integer(restingHR),
                fitbitsleeplogs = as.integer(fitbitsleeplogs),
                otherData = as.integer(otherData)) %>% 
  ungroup() 
```

### Plots of Fitbit Sleep data vs other forms of Fitbit Data (dailydata, restingHR, activitylogs, sleeplogs)
For a given participant, we check for each day if have a record for the various data types. Each record is a day for a participant. So the intersection size is the number of "day-participant" instances that we have data, for that specific data type. 

```{r sleep vs dailydata-restingHR-activitylogs,  echo=FALSE, warning=FALSE, message=FALSE, fig.height=8, fig.width=15}
library(UpSetR)
upset(as.data.frame(aa3),
      sets = c('dailydata','restingHR', 'activitylogs', 'fitbitsleeplogs'),
      order.by = "freq")
```

```{r sleep vs other data as a whole,  echo=FALSE, warning=FALSE, message=FALSE, fig.height=8, fig.width=15}

upset(as.data.frame(aa3),
      sets = c('otherData', 'fitbitsleeplogs'),
      order.by = "freq")
```

### Code used 
```{r get provenance, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
### Commenting out - doesnt work across users without 
githubr::setGithubToken(gtToken)
thisFileName <- "dashboards/Sleep/dashboard_fitbit_sleep_vs_otherData.Rmd" # location of file inside github repo
thisRepo <- githubr::getRepo(repository = "itismeghasyam/RECOVER-MHDR-Analysis",
                    ref="branch",
                    refName="main")
thisFile <- githubr::getPermlink(repository = thisRepo, repositoryPath=thisFileName)
```

```{r print provenance, echo=FALSE, results='asis'}
http_address <- glue::glue("{thisFile}")
cat("[GitHub Code](", http_address, ")")
```
